### ISSUE TITLE
Cache versionning in Rails 6

### ISSUE THREAD

**Issue by ssaunier** [redis-store/redis-activesupport#117]
Dear maintainers,

I am currently testing the upgrade of a Rails app from `5.2.3` to `6.0.0.rc1`. In the [official migration guide](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#public-api), there is a mention of this command to check that everything is working with the new gem loader:

```bash
bin/rails zeitwerk:check
```

I ran it on my app which happens to have the following configuration for `development` and `production` environments:

```ruby
# config/environments/*.rb

if ENV['DISABLE_CACHE'] == 'true'
  config.cache_store = :null_store
else
  config.cache_store = :redis_store, 'redis://localhost:6379/0/cache', { expires_in: 1.hour }
end
```

The `redis_store` is available thanks to the latest [`redis-rails`](https://github.com/redis-store/redis-rails) gem added to my `Gemfile`.

Here is the error message that `zeitwerk:check` gives after a `bundle update rails` to `6.0.0.rc1`:

```bash
rails aborted!

You're using a cache store that doesn't support native cache versioning.
Your best option is to upgrade to a newer version of ActiveSupport::Cache::RedisStore
that supports cache versioning (ActiveSupport::Cache::RedisStore.supports_cache_versioning? #=> true).

Next best, switch to a different cache store that does support cache versioning:
https://guides.rubyonrails.org/caching_with_rails.html#cache-stores.

To keep using the current cache store, you can turn off cache versioning entirely:

    config.active_record.cache_versioning = false

/Users/seb/code/lewagon/www/config/environment.rb:5:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => zeitwerk:check => environment
(See full trace by running task with --trace)
```

Adding the suggested line to `config/application.rb` allows the command to run successfully but I wonder if there is so plan to support this Rails 6 feature?

Thank you very much!

**Comment by tubbo** [comment]
Hi @ssaunier, we recommend the usage of Rails' built-in RedisCacheStore rather than using RedisStore for your Rails cache. Although RedisStore is still useful as a backend for your `Rack::Cache`, Rack session storage, and Sinatra cache, Rails' built-in store is going to be a lot better maintained given their resources (I am the only active maintainer of the redis-store projects).

Here's where we mention in the README that we're basically sunsetting support for this project going forward: https://github.com/redis-store/redis-activesupport#a-quick-note-about-rails-52. I'd like to state again that we're _not_ dropping everything, just `redis-activesupport`. `redis-rack-cache`, `redis-sinatra`, and `redis-rack` are still under active development.
