### ISSUE TITLE
Client option for store creation is setting @data to a Redis client, not a Redis store

### ISSUE THREAD

**Issue by tldev** [redis-store/redis-activesupport#127]
Hello,

I was attempting to memoize our `Redis` client and re-use it to create future `ActiveSupport::Cache::RedisStore` instances, but realized quickly that the implementation isn't quite right.

Referencing:
https://github.com/redis-store/redis-activesupport/blob/master/lib/active_support/cache/redis_store.rb#L69

The initializer is setting `@data` to the `Redis` client which is expected to be a `Redis::Store` or connection pool. This could just purely be a documentation issue, but the [test itself](https://github.com/redis-store/redis-activesupport/pull/104/files#diff-35895d085a7dea11346b6e463896c20a3f075e8b67ec752a865427c8d40df51eR30) is a bit misleading.

Side-problem, maybe someone has insight into, I don't see a way of creating a `Redis::Store` with an existing `Redis` client, so either way, it's not very useful.

**Comment by tubbo** [comment]
Yeah, I guess you'd want to use a `Redis::Store` there rather than a `Redis` client. This is the underlying client library that all of the redis-store gems use to talk to your Redis server. [Redis::Store is a subclass of the Redis client](https://github.com/redis-store/redis-store/blob/master/lib/redis/store.rb#L13), so the APIs are relatively similar, but I'm not sure just using a raw `Redis` client will work since we have some additional logic for TTLs and serialization.
