### ISSUE TITLE
Compatibility with Rails 4

### ISSUE THREAD

**Issue by AmirMingaliev** [redis-store/redis-activesupport#79]
Hi guys. There is some compatibility issue regarding `master` branch and `5.0.2` release version. 

I'm trying to use `master` branch, which contains changes from jbuilder_multi_cache compatibility, but `bundle install` fails. It happens, because 'redis-activesupport` depends on `redis-rails 5.0.1`, which depends on `redis-actionpack 5.0.1`, which depends on `redis-rack 2.0.0`, which depends on `rack ~> 2.0.0`. But meanwhile Rails 4 depends on `rake ~> 1.6.0`. So the new version of `redis-activesupport` works with Rails 5+ version only.

I'm also described this problem in #78.

**Comment by tubbo** [comment]
@AmirMingaliev Changes to the master branch of this and all redis-store repos are intended for use with the most recently released version of their counterparts, like Rack, ActiveSupport, or Rails itself. Therefore, the changes I review and accept are assumed to be for the latest version unless otherwise noted. Since taking on the maintenance of these gems, I haven't really seen any requests for backported fixes, but I will gladly make you a branch and release a backported fix of your feature.

In the future, I would advise informing me (or any maintainer, really) of the version of their library you're installing, so they can apply your fix to the proper branch. Or, in this case, actually create a branch for your fix to go on.

Are you using *v4.0.0* or one of the *v4.1.x* releases?

**Comment by AmirMingaliev** [comment]
@tubbo we're using:
```ruby
rails (= 4.2.5.1)
redis-rails (5.0.1)
redis-activesupport (5.0.1)
```

**Comment by tubbo** [comment]
Interesting, v5.0 wasn't really supposed to be compatible with v4.x of Rails. We at least didn't intend on it being compatible. I'm going to branch off the latest redis-activesupport v4.1.x release and try to merge your branch into it.

**Comment by AmirMingaliev** [comment]
@tubbo thanks 👍 Hope it will work for us :)

**Comment by AmirMingaliev** [comment]
Hi @tubbo. While preparing #81 I have found that `redis-activesupport 4.1.5` is a part of `redis-rails  4.0.0`, which is very old and doesn't have [redis sentinel](https://redis.io/topics/sentinel) support. But we strongly need this feature. 

Also while doing #78 and #74 I have tested `redis-rails 5.0.1` gem in `rails 4.2.5.1` with our team and gems work smoothly. So  my question is there a way to add jbuilder_cache_multi changes to 5.0.1 version and make it compatible with `rails 4`? Or maybe you will suggest some another way  :)

Thanks in advance
