### ISSUE TITLE
`exist?` method returns `ArgumentError`

### ISSUE THREAD

**Issue by ntkm** [redis-store/redis-activesupport#84]
successfully write.
However, cannot read!

```
[37] pry(main)> redis.write('foo', 'bar')
=> "OK"
[48] pry(main)> redis.exist?('foo')
ArgumentError: wrong number of arguments (given 2, expected 1)
from /path-to-redis.rb:787:in `get'
redis.read('foo')
ArgumentError: wrong number of arguments (given 2, expected 1)
from /path-to-redis.rb:787:in `get'
```

Certainly, I set value on Redis
```
pry(main)> redis = Redis.new host: redis_servers, port: 6379, db: 1
=> #<Redis client v3.2.1 for redis://localhost:6379/1>
[46] pry(main)> redis.get('foo')
=> "bar"
```

**Comment by tubbo** [comment]
@ntkm hey thanks for this, it does seem like the signature passed to `super` is wrong for the `exist?` method, and down in our implementation of `read_entry` we are passing options to the `get` method. we probably don't want to be doing that.

line 251 of **lib/active_support/cache/redis_store.rb** needs to be replaced with:

```ruby
entry = with { |c| c.get key }
```

so that it doesn't pass options to the key.

**Comment by tubbo** [comment]
@ntkm which rails version are you using? I cannot reproduce this when testing against ActiveSupport v5.1.2, Rails v5.1.2, and Redis::ActiveSupport v5.0.3.

**Comment by ntkm** [comment]
@tubbo 
oh... I used v4.x.x...(too old!)
if not reproduce on v5.x.x, this issued should be closed, I think

**Comment by tubbo** [comment]
ok thanks @ntkm
